### ISSUE TITLE
markbot msg confusion

### ISSUE THREAD

**Issue by jud3bl4nk** [jud3bl4nk/modularity-mindfulness#1]
Hi,
I'm getting the following error from markbot and I'm not sure what needs to be changed...

"Website isn’t functioning as expected: the background-colour, color or border-colour of the navigation links don’t change when hovered"

thanks 

@charlie-quinn

**Comment by charlie-quinn** [comment]
- [ ] by removing the links' underline using `text-decoration: none`, and adding the `border-bottom` property, we have total control over how the underline styling can look:
`.nav a {
  border-bottom: .1em solid #8bc9d9;
  text-decoration: none;
  color: #005e76;
}`
- [ ] hover styling for ☝️
`.nav a:hover {
  border-color: #0084a6;
  color: #005e76;
}`
- [ ] adjust button styling to match:
`.btn-ghost {
  border-width: .1em;
  border-color: #8bc9d9;
  color: #005e76;
}`
- [ ] adjust button's hover styling to match:
`.btn-ghost:hover {
  background-color: #8bc9d9;
  border-color: #005e76;
  color: #000;
}`

**Comment by charlie-quinn** [comment]
⚠️`Reminder: please close this issue once it has been resolved.`
